/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Badge: typeof import('./src/components/Badge.vue')['default']
    Bubble: typeof import('./src/components/Bubble.vue')['default']
    ChatObject: typeof import('./src/components/ChatObject.vue')['default']
    CopyBox: typeof import('./src/components/CopyBox.vue')['default']
    DragBar: typeof import('./src/components/DragBar.vue')['default']
    EmptyData: typeof import('./src/components/EmptyData.vue')['default']
    FileIcon: typeof import('./src/components/FileIcon.vue')['default']
    FileItem: typeof import('./src/components/FileItem.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Icons1: typeof import('./src/components/Icons1.vue')['default']
    ImageViewer: typeof import('./src/components/ImageViewer.vue')['default']
    LabelBox: typeof import('./src/components/LabelBox.vue')['default']
    LabelGroup: typeof import('./src/components/LabelGroup.vue')['default']
    LayoutItem: typeof import('./src/components/LayoutItem.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MessageProview: typeof import('./src/components/MessageProview.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    PageContent: typeof import('./src/components/PageContent.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    PlayIcon: typeof import('./src/components/PlayIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollView: typeof import('./src/components/ScrollView.vue')['default']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    ServiceStatus: typeof import('./src/components/ServiceStatus.vue')['default']
    SessionItem: typeof import('./src/components/SessionItem.vue')['default']
    TabList: typeof import('./src/components/TabList.vue')['default']
    Text: typeof import('./src/components/Text.vue')['default']
    TextViewer: typeof import('./src/components/TextViewer.vue')['default']
    TooBar: typeof import('./src/components/TooBar.vue')['default']
    UploadPortrait: typeof import('./src/components/UploadPortrait.vue')['default']
    Url: typeof import('./src/components/Url.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
    Wave: typeof import('./src/components/Wave.vue')['default']
  }
}
