
const a = {
    selectUserId: 'string',
    id: 'string',
    titleContent: 'string',
    titleDescribe: 'string',
    completionTime: '2024-03-25T10:15:16.878Z',
    taskType: 'string',
    publishUserId: 'string',
    headUserId: 'string',
    selectType: 0,
    deptIdList: ['string'],
    rolesIdList: ['string'],
    gradeList: ['string'],
    userIdList: ['string'],
    fileList: [
      {
        id: 'string',
        titleInfoReportId: 'string',
        encName: 'string',
        encPath: 'string',
        encType: 'string',
        encSize: 'string',
        encSuffix: 'string',
        encUrl: 'string',
        encProperty: 0,
        encStoreMark: 0,
        encBigType: 0,
      },
    ],
  };
  
//   RC.WebApp.WebApi.ApiControllers.AppFunctions.Training.Model.Achievements.AmTitleReportInput {
//     selectUserId (string, optional): 选择身份Id ,
//     id (string, optional): 主键 ,
//     titleContent (string, optional): 任务名称 ,
//     titleDescribe (string, optional): 任务说明 ,
//     completionTime (string, optional): 预计完成时间 ,
//     taskType (string, optional): 任务类型 ,
//     publishUserId (string, optional): 发布人id ,
//     headUserId (string, optional): 负责人id ,
//     selectType (integer, optional): 选择类型 1 部门+人 2 岗位+人 ,
//     deptIdList (Array[string], optional): 部门范围 ,
//     rolesIdList (Array[string], optional): 岗位范围 ,
//     gradeList (Array[string], optional): 职级范围 ,
//     userIdList (Array[string], optional): 人员范围 ,
//     fileList (Array[RC.Application.Achievements.RC_AchievementsModule.AM_TitleInfo.Dtos.AmTitleInfoReportFileSaveDto], optional): 附件列表
//     }


  var formdata = {
    id: this.titleInfoId,
    selectUserId: this.selectUserId,
    titleContent: this.topic,
    titleDescribe: this.titleDescribe,
    amTitleOptionList: this.choiseOptions,
    completionTime: this.isCompletionTimeEnabled ? this.completionTime : null,
    remindMark: Number(this.isReminderEnabled),
    remindDateList: this.isReminderEnabled ? this.reminders.filter(x => x.value && x.value.length != 0).map(x =>
        x.value) : [],
    roundType: cyclePeriods[this.cyclePeriod].title,
    roundTime: this.cyclePeriod,
    isAuto: Number(this.isAutomaticAssign),
    checkMark: Number(this.isCheckMark),
    score: this.score, //比例分数-自动则后计算 ,
    // "deptIds": orgArgs.depIdList,
    // "rolesIds": orgArgs.posiIdList,
    // "userIds": orgArgs.userIdList,
    selectType, //选择类型 1 部门+人 2 岗位+人 ,
    deptIdList: orgArgs.depIdList.map(x => x.id),
    rolesIdList: orgArgs.posiIdList.map(x => x.id),
    userIdList: orgArgs.userIdList.map(x => x.userID),
    gradeList: orgArgs.gradeList.map(x => x.id),
    titleTypeId1: this.tabId,
    titleTypeCode1: this.tabCode,
    titleTypeId2: this.typeId,
    titleTypeCode2: this.typeCode,
    titleTypeId3: this.titleTypeId3,
    titleTypeCode3: this.titleTypeCode3,
    belongSystem: this.belongSystem,
    parentId1: '',
    parentId2: '',


    taskType: 'string',
    publishUserId: 'string',
    headUserId: 'string',
    fileList: [{
        id: 'string',
        titleInfoReportId: 'string',
        encName: 'string',
        encPath: 'string',
        encType: 'string',
        encSize: 'string',
        encSuffix: 'string',
        encUrl: 'string',
        encProperty: 0,
        encStoreMark: 0,
        encBigType: 0,
    }, ],

}